export const USER_REGISTER_REQUEST = "USER_REGISTER_REQUEST";
export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS";
export const USER_REGISTER_FAIL = "USER_REGISTER_FAIL";

export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAIL = "USER_LOGIN_FAIL";

export const USER_LOGOUT_REQUEST = "USER_LOGOUT_REQUEST";
export const USER_LOGOUT_SUCCESS = "USER_LOGOUT_SUCCESS";
export const USER_LOGOUT_FAIL = "USER_LOGOUT_FAIL";

export const SERT_USER = "SERT_USER";

export const USER_GOOGLE_SIGN_IN_REQUEST = "USER_GOOGLE_SIGN_IN_REQUEST";
export const USER_GOOGLE_SIGN_IN_SUCCESS = "USER_GOOGLE_SIGN_IN_SUCCESS";
export const USER_GOOGLE_SIGN_IN_FAIL = "USER_GOOGLE_SIGN_IN_FAIL";

export const USER_RESET = "USER_RESET";
